### ISSUE TITLE
2020.3.33打卡源工程报错。

### ISSUE THREAD

**Issue by Li721x** [Giresharu/TMPro-Player#3]
[TMPro-Player-master.zip](https://github.com/Giresharu/TMPro-Player/files/11862465/TMPro-Player-master.zip)
在github上下载的源工程，2020.3.33打开，首先是
![image](https://github.com/Giresharu/TMPro-Player/assets/41276858/29608ebd-e824-45f5-90e7-076213e2b851)
这个报错，然后注释。最后是这个，不知道怎么修改
![image](https://github.com/Giresharu/TMPro-Player/assets/41276858/1d2ffe1f-3bb5-492f-bc8e-7669adf0e02f)

**Comment by Giresharu** [comment]
看了一下你的项目结构，你直接把工程导入 Assets 自然会报 Icon 的错。请你按照 ReadMe 提供的两个安装方法来安装。
第二个语法新特性的问题，在我这边通过2020.3.33打开你的工程并没有报这个错误

**Comment by Giresharu** [comment]
已修复，openupm源可能会稍晚更新，如果着急可以先使用 git url 安装
